//lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIG8EkkesAKs-E8sL6vXc8flbEYhCBEBw',
    appId: '1:1078197154358:web:aba64f008d3ec502a01e97',
    messagingSenderId: '1078197154358',
    projectId: 'flozendmemory',
    authDomain: 'flozendmemory.firebaseapp.com',
    storageBucket: 'flozendmemory.firebasestorage.app',
    measurementId: 'G-X45YNTFXMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Inyj1d7U6DkdyiTjb1Rm0SAE_cjxT60',
    appId: '1:1078197154358:android:7197438f0cfdeb62a01e97',
    messagingSenderId: '1078197154358',
    projectId: 'flozendmemory',
    storageBucket: 'flozendmemory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBdMmh-ZjFqpwKOoUaLJXbRF5Pa8fhNt8',
    appId: '1:1078197154358:ios:c71b31268d83a015a01e97',
    messagingSenderId: '1078197154358',
    projectId: 'flozendmemory',
    storageBucket: 'flozendmemory.firebasestorage.app',
    iosBundleId: 'com.example.memoryDiggingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBdMmh-ZjFqpwKOoUaLJXbRF5Pa8fhNt8',
    appId: '1:1078197154358:ios:c71b31268d83a015a01e97',
    messagingSenderId: '1078197154358',
    projectId: 'flozendmemory',
    storageBucket: 'flozendmemory.firebasestorage.app',
    iosBundleId: 'com.example.memoryDiggingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIG8EkkesAKs-E8sL6vXc8flbEYhCBEBw',
    appId: '1:1078197154358:web:32f7ec88860c6377a01e97',
    messagingSenderId: '1078197154358',
    projectId: 'flozendmemory',
    authDomain: 'flozendmemory.firebaseapp.com',
    storageBucket: 'flozendmemory.firebasestorage.app',
    measurementId: 'G-RRJKVEYWPM',
  );

}