//lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNFrS70mbgIjeX-BCUDzvsKQ0jKIvJZCM',
    appId: '1:264211385958:web:b7420a6c80d0d9d008a7a7',
    messagingSenderId: '264211385958',
    projectId: 'frozenedmemories',
    authDomain: 'frozenedmemories.firebaseapp.com',
    storageBucket: 'frozenedmemories.firebasestorage.app',
    measurementId: 'G-WZ8WL9YCBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgoszdpdMWbMh62UNdukmCKRVm4FNSaLs',
    appId: '1:264211385958:android:8610e1d427fa725e08a7a7',
    messagingSenderId: '264211385958',
    projectId: 'frozenedmemories',
    storageBucket: 'frozenedmemories.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBdMmh-ZjFqpwKOoUaLJXbRF5Pa8fhNt8',
    appId: '1:1078197154358:ios:c71b31268d83a015a01e97',
    messagingSenderId: '1078197154358',
    projectId: 'flozendmemory',
    storageBucket: 'flozendmemory.firebasestorage.app',
    iosBundleId: 'com.example.memoryDiggingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBdMmh-ZjFqpwKOoUaLJXbRF5Pa8fhNt8',
    appId: '1:1078197154358:ios:c71b31268d83a015a01e97',
    messagingSenderId: '1078197154358',
    projectId: 'flozendmemory',
    storageBucket: 'flozendmemory.firebasestorage.app',
    iosBundleId: 'com.example.memoryDiggingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIG8EkkesAKs-E8sL6vXc8flbEYhCBEBw',
    appId: '1:1078197154358:web:32f7ec88860c6377a01e97',
    messagingSenderId: '1078197154358',
    projectId: 'flozendmemory',
    authDomain: 'flozendmemory.firebaseapp.com',
    storageBucket: 'flozendmemory.firebasestorage.app',
    measurementId: 'G-RRJKVEYWPM',
  );

}